version: '3.9'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  nodejs-app:
    build: .
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    entrypoint: "node index.js"
    environment:
      - NODE_ENV=development

